name: CI

on:
  push: {}

jobs:
  lint-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ 16 ]
    name: Lint & Build
    steps:
      - uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - uses: pnpm/action-setup@v2.2.4
        name: Setup pnpm
        with:
            version: 7
      - run: pnpm install --frozen-lockfile
      - run: pnpm lint
      - run: pnpm build