name: CI

on:
  push: {}

jobs:
  lint-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ 20 ]
    name: Lint & Build
    steps:
      - uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
      - uses: pnpm/action-setup@v4.1.0
        name: Setup pnpm
        with:
            version: 8
      - run: pnpm install --frozen-lockfile
      - run: pnpm lint
      - run: pnpm build